MVCUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrackerLibrary;
using TrackerLibrary.Models;

namespace MVCUI.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            List<TournamentModel> tournaments = GlobalConfig.Connection.GetTournaments_All();

            return View(tournaments);
        }

    }
}

MVCUI/Controllers/TournamentsController.cs
using MVCUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrackerLibrary;
using TrackerLibrary.Models;

namespace MVCUI.Controllers
{
    public class TournamentsController : Controller
    {
        // GET: Tournaments
        public ActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Create()
        {
            TournamentMVCModel input = new TournamentMVCModel();

            List<TeamModel> allTeams = GlobalConfig.Connection.GetTeams_All();
            List<PrizeModel> allPrizes = GlobalConfig.Connection.GetPrizes_All();

            input.EnteredTeams = allTeams.Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.TeamName }).ToList();
            input.Prizes = allPrizes.Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.PlaceName }).ToList();

            return View(input);
        }

        // POST: Tournaments/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TournamentMVCModel model)
        {
            try
            {
                if (ModelState.IsValid && model.SelectedEnteredTeams.Count > 1)
                {
                    TournamentModel tmt = new TournamentModel();

                    tmt.TournamentName = model.TournamentName;
                    tmt.EntryFee = model.EntryFee;
                    tmt.EnteredTeams = model.SelectedEnteredTeams.Select(x => new TeamModel { Id = int.Parse(x) }).ToList();
                    tmt.Prizes = model.SelectedPrizes.Select(x => new PrizeModel { Id = int.Parse(x) }).ToList();
                    TournamentLogic.CreateTournamentRounds(tmt);

                    GlobalConfig.Connection.CreateTournament(tmt);

                    tmt.AlertUsersToNewRound();

                    return RedirectToAction("Index");
                }
                else
                {
                    List<TeamModel> allTeams = GlobalConfig.Connection.GetTeams_All();
                    List<PrizeModel> allPrizes = GlobalConfig.Connection.GetPrizes_All();

                    model.EnteredTeams = allTeams
                        .Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.TeamName, Selected = model.SelectedEnteredTeams.Contains(x.Id.ToString()) })
                        .ToList();
                    model.Prizes = allPrizes
                        .Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.PlaceName, Selected = model.SelectedPrizes.Contains(x.Id.ToString()) })
                        .ToList();
                    return View(model);
                }
            }
            catch
            {
                return RedirectToAction("Create");
            }
        }
    }
}

MVCUI/Views/Home/Index.cshtml
@model IEnumerable<TrackerLibrary.Models.TournamentModel>

@{
    ViewBag.Title = "Home Page";
}


<div class="row drop-30">
    <div class="col-md-8">
        <div class="jumbotron">
            <h1>Office Fun!</h1>
            <p class="lead">Track your in office tournaments easily and have a great time doing it.</p>
            <p>@Html.ActionLink("Create a Tournament", "Create", "Tournaments", new { @class = "btn btn-primary btn-lg" })</p>
        </div>
        <div class="row">
            <div class="col-md-6">
                <h2>Play with Friends</h2>
                <p>
                    Get a team and get started today on a new tournament.
                </p>
            </div>
            <div class="col-md-6">
                <h2>Win Prizes</h2>
                <p>Setup a tournament with prizes with first and second place and compete to win.</p>
            </div>
       </div>
    </div>
    <div class="col-md-4">
        <h2>Current Tournaments</h2>
        <ul class="list-unstyled active-tournaments">
            @foreach (var item in Model)
            {
                <li><a href="/">@item.TournamentName</a></li>
            }

        </ul>
    </div>
</div>